### ISSUE TITLE
Apply CSS enhancements in build time

### ISSUE THREAD

**Issue by gustavohenke** [gustavohenke/bselect#15]
CSS enhancements should be done when building bselect.
The goal is to eliminate cases where a selector has 2 properties of the same type, for example:

``` css
.bselect {
   padding: 4px 10px;
   padding-left: 15px;
}
```

Will try to find out how to do that with Grunt.
